"""Convert article markdown to WeChat-compatible HTML with inline CSS.

Handles the specific article structure generated by wechat_writer:
  - Curly-quoted preface paragraph
  - Three numbered sections (基本面分析 / 比赛走势 / 赛果预测)
  - Bold team-name leads (**TeamName**)
  - Recommendation box (推荐：/ 比分：)
"""
from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# Inline CSS constants
# ---------------------------------------------------------------------------
_WRAP = (
    "font-family: -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif;"
    " font-size: 16px; line-height: 1.8; color: #333; padding: 0 16px;"
)
_H2 = (
    "font-size: 17px; font-weight: bold; color: #07c160;"
    " margin: 28px 0 14px; padding-bottom: 8px; border-bottom: 2px solid #07c160;"
)
_PARA = "margin: 0 0 16px; line-height: 1.9; color: #333;"
_PREFACE = (
    "margin: 0 0 20px; font-size: 15px; line-height: 1.9; color: #555;"
    " background: #f7f7f7; padding: 14px 16px;"
    " border-left: 4px solid #07c160; border-radius: 4px;"
)
_BOX = (
    "background: #f0faf4; border: 1px solid #07c160;"
    " border-radius: 8px; padding: 16px 20px; margin: 20px 0;"
)
_BOX_LINE = "margin: 0 0 6px; font-size: 15px; color: #222;"

_SECTION_LABELS = {"1": "一、基本面分析", "2": "二、比赛走势", "3": "三、赛果预测"}


def _apply_bold(text: str) -> str:
    """Convert **…** to <strong> with inline style."""
    return re.sub(r"\*\*(.+?)\*\*", r'<strong style="color: #222;">\1</strong>', text)


def markdown_to_wechat_html(markdown_text: str) -> str:
    """Convert article markdown body to WeChat-compatible HTML (inline CSS only)."""
    lines = markdown_text.strip().splitlines()
    parts: list[str] = []

    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.strip()
        i += 1

        # Skip blank lines
        if not line:
            continue

        # Skip H1 / H2 markdown headings (title row)
        if re.match(r"^#{1,2}\s", line):
            continue

        # Curly-quoted preface — "\u201c...\u201d" or plain "..."
        if (line.startswith("\u201c") and line.endswith("\u201d")) or (
            line.startswith('"') and line.endswith('"') and len(line) > 4
        ):
            inner = line[1:-1]
            parts.append(f'<p style="{_PREFACE}">{_apply_bold(inner)}</p>')
            continue

        # Numbered section heading: "1. 基本面分析"
        m = re.match(r"^(\d)\.\s+\S", line)
        if m:
            num = m.group(1)
            label = _SECTION_LABELS.get(num, line)
            parts.append(f'<h2 style="{_H2}">{label}</h2>')
            continue

        # Recommendation block — collect until blank line
        if re.match(r"^推荐[：:]", line):
            box_lines = [line]
            while i < len(lines):
                nxt = lines[i].strip()
                if not nxt:
                    i += 1
                    break
                box_lines.append(nxt)
                i += 1
            items = "".join(
                f'<p style="{_BOX_LINE}">{_apply_bold(l)}</p>' for l in box_lines
            )
            parts.append(f'<section style="{_BOX}">{items}</section>')
            continue

        # Standalone 比分 line (already captured above, skip if orphaned)
        if re.match(r"^比分[：:]", line):
            continue

        # Regular paragraph
        parts.append(f'<p style="{_PARA}">{_apply_bold(line)}</p>')

    body = "\n\n".join(parts)
    return f'<section style="{_WRAP}">\n\n{body}\n\n</section>'
